=== vyomtandon/ff4j/ff4j-core/src/main/resources/ff4j-1.2.0.xsd
<xs:schema xmlns="http://www.ff4j.org/schema/ff4j" 
		   targetNamespace="http://www.ff4j.org/schema/ff4j"
		   attributeFormDefault="unqualified"
		   elementFormDefault="qualified" 
		   xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- Root Element -->
	<xs:element name="features">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded" minOccurs="0">

				<!-- Element Feature -->
				<xs:element name="feature" type="featureType" maxOccurs="unbounded" minOccurs="0" />

				<!-- Element FeatureGroup -->
				<xs:element name="feature-group" maxOccurs="unbounded"
					minOccurs="0">
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded" >
							<xs:element name="feature" type="featureType" />
						</xs:sequence>
						<xs:attribute type="xs:string" name="name" use="required" />
					</xs:complexType>
				</xs:element>

			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="featureType" mixed="true">
		<xs:choice maxOccurs="unbounded" minOccurs="0">

			<!-- Security -->
			<xs:element name="security" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence minOccurs="1" maxOccurs="unbounded">
						<xs:element name="role">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute type="xs:string" name="name" use="required" />
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<!-- FlipStrategy -->
			<xs:element name="flipstrategy" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="param">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute type="xs:string" name="name"  use="required" />
										<xs:attribute type="xs:string" name="value" use="optional" />
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute type="xs:string" name="class" use="required"/>
				</xs:complexType>
			</xs:element>

		</xs:choice>
		<xs:attribute type="xs:string" name="uid" use="required"/>
		<xs:attribute type="xs:string" name="description" use="optional" />
		<xs:attribute type="xs:boolean" name="enable" use="required"	 />
	</xs:complexType>

</xs:schema>

=== vyomtandon/ff4j/ff4j-core/src/test/resources/test-strategy-officehour.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  #%L
  ff4j-core
  %%
  Copyright (C) 2013 Ff4J
  %%
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  #L%
  -->

<features xmlns="http://www.ff4j.org/schema/ff4j" 
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://www.ff4j.org/schema/ff4j ../../main/resources/ff4j-1.2.0.xsd">

	<!-- No Expression -->
	<feature uid="first" enable="true" description="some desc">
		<flipstrategy class="org.ff4j.strategy.time.OfficeHourStrategy" >
			<param name="monday"    	 value="08:00-12:00,13:30-18:00" />
			<param name="tuesday"   	 value="08:00-12:00,13:30-18:00" />
			<param name="wednesday" 	 value="08:00-12:00,13:30-18:00" />
			<param name="thursday"  	 value="08:00-12:00,13:30-18:00" />
			<param name="friday" 		 value="08:00-12:00,13:30-18:00" />
			<param name="saturday" 		 value="10:00-19:00" 			/>
			<param name="sunday" 		 value="" />
			<param name="publicHolidays" value="2015-01-01,2015-05-01,2015-12-25" />
			<param name="specialOpenings" value="[08:00-12:00]@2015-01-01;[08:00-12:00]@2015-01-02" />
		</flipstrategy>
	</feature>
		
</features>

=== vyomtandon/ff4j/ff4j-core/src/test/resources/test-featureXmlParserTest-ok.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  #%L
  ff4j-core
  %%
  Copyright (C) 2013 Ff4J
  %%
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  #L%
  -->

<features xmlns="http://www.ff4j.org/schema/ff4j" 
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://www.ff4j.org/schema/ff4j ../../main/resources/ff4j-1.2.0.xsd">


	<feature-group name="group1">
	</feature-group>
	
	<feature-group name="group2">
		<feature uid="f1" enable="true" description="abc" />
		<feature uid="f2" enable="false" description="def" />
		<feature uid="f3" enable="true" description="ghj" />
	</feature-group>

	<feature-group name="group3">
		<feature uid="f0" enable="true" description="description">
			<flipstrategy class="org.ff4j.strategy.el.ExpressionFlipStrategy">
				<param name="expression"><![CDATA[A | B]]></param>
			</flipstrategy>
			<security>
				<role name="X" />
				<role name="Y" />
			</security>
		</feature>
	</feature-group>

	<feature uid="f4" enable="true" description="description">
		<flipstrategy class="org.ff4j.strategy.time.ReleaseDateFlipStrategy">
			<param name="releaseDate" value="2013-07-14-14:00" />
		</flipstrategy>
	</feature>
	
	<feature uid="f6" enable="true" description="description">
		<flipstrategy class="org.ff4j.strategy.time.ReleaseDateFlipStrategy">
			<param name="releaseDate">2013-07-14-14:00</param>
		</flipstrategy>
	</feature>
	
	<feature uid="f5" enable="true" >
		<security>
			<role name="X" />
			<role name="Y" />
		</security>
	</feature>

</features>

=== vyomtandon/ff4j/ff4j-webapi-jersey2x/src/test/resources/test-ff4j-features.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  #%L
  ff4j-core
  %%
  Copyright (C) 2013 Ff4J
  %%
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  #L%
  -->
<features xmlns="http://www.ff4j.org/schema/ff4j" 
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://www.ff4j.org/schema/ff4j http://ff4j.org/schema/ff4j-1.2.0.xsd">

	<feature uid="AwesomeFeature" enable="true" description="some desc" >
		<flipstrategy class="org.ff4j.strategy.ClientFilterStrategy">
			<param name="grantedClients" value="C1,C2" />
		</flipstrategy>
	</feature>
	
	<feature uid="first" enable="true" description="description" >
		<security>
			<role name="USER" />
		</security>
	</feature>
	
	<feature-group name="GRP0">
		<feature uid="second" enable="false" description="description" >
			<security>
				<role name="USER" />
			</security>
		</feature>
	</feature-group>
	
	
	<feature-group name="GRP1">
	
		<feature uid="forth" enable="true" description="description" >
			<flipstrategy class="org.ff4j.strategy.el.ExpressionFlipStrategy">
				<param name="expression" value="third | second" />
			</flipstrategy>
			<security>
				<role name="ADMINISTRATOR" />
				<role name="BETA-TESTER" />
			</security>
		</feature>
		
		<feature uid="third" enable="false" >
			<security>
				<role name="ADMINISTRATOR" />
				<role name="BETA-TESTER" />
			</security>
		</feature>
	
	</feature-group>
	
</features>
