=== vyomtandon/ff4j/ff4j-core/src/main/resources/ff4j-1.4.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.ff4j.org/schema/ff4j" 
		   targetNamespace="http://www.ff4j.org/schema/ff4j"
		   attributeFormDefault="unqualified"
		   elementFormDefault="qualified" 
		   xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" 
		    vc:minVersion="1.1" >
		    
	<xs:element name="ff4j">
		<xs:annotation>
			<xs:documentation>FF4J root configuration tag</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="features" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="properties" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="features">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="feature"/>
				<xs:element ref="feature-group"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="properties">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="property"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="feature" type="featureType">
		<xs:annotation>
			<xs:documentation>Core feature</xs:documentation>
		</xs:annotation>
	</xs:element>
	
	<xs:element name="feature-group">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="feature"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="property" type="propertyType"/>
	
	<xs:complexType name="featureType" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<!-- Security -->
			<xs:element name="security" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence minOccurs="1" maxOccurs="unbounded">
						<xs:element name="role">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="name" type="xs:string" use="required"/>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<!-- FlipStrategy -->
			<xs:element name="flipstrategy" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="param">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="name" type="xs:string" use="required"/>
										<xs:attribute name="value" type="xs:string" use="optional"/>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="class" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="custom-properties" minOccurs="0">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element ref="property"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:choice>
		<xs:attribute name="uid" type="xs:string" use="required"/>
		<xs:attribute name="enable" type="xs:boolean" use="required"/>
		<xs:attribute name="description" type="xs:string" use="optional"/>
	</xs:complexType>
	
	<xs:complexType name="propertyType">
		<xs:sequence minOccurs="0">
			<xs:element name="fixedValues">
				<xs:complexType>
					<xs:sequence maxOccurs="unbounded">
						<xs:element name="value"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" 		 type="xs:string" use="required" />
		<xs:attribute name="value"		 type="xs:string" use="required" />
		<xs:attribute name="type" 		 type="xs:string" use="optional" />
		<xs:attribute name="description" type="xs:string" use="optional" />
	</xs:complexType>
	
</xs:schema>

=== vyomtandon/ff4j/ff4j-aop/src/test/resources/ff4j-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- #%L ff4j-core %% Copyright (C) 2013 Ff4J %% Licensed under the Apache 
	License, Version 2.0 (the "License"); you may not use this file except in 
	compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 
	Unless required by applicable law or agreed to in writing, software distributed 
	under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES 
	OR CONDITIONS OF ANY KIND, either express or implied. See the License for 
	the specific language governing permissions and limitations under the License. 
	#L% -->
<ff4j xmlns="http://www.ff4j.org/schema/ff4j" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ff4j.org/schema/ff4j http://ff4j.org/schema/ff4j-1.4.0.xsd">

	<features>
		<feature uid="AwesomeFeature" enable="true" />
	</features>
	
	<properties>
		<property name="a" value="AMER">
			<fixedValues>
				<value>AMER</value>
				<value>EAST</value>
				<value>EAST</value>
				<value>EAST</value>
			</fixedValues>
		</property>
		
		<property name="today" value="2015-08-31 12:12:00"  type="org.ff4j.property.PropertyDate" />
		
		<property name="pExo" value="Yihaaaa"  type="org.ff4j.placeholder.PropertyExotic" />
		
		<property name="c" value="12.5"  type="org.ff4j.property.PropertyDouble" />
		
		<property name="d" value="true"  type="org.ff4j.property.PropertyBoolean" />
		
		<property name="e" value="hello" />
		
		<property name="pInt" value="1" type="org.ff4j.property.PropertyInt">
			<fixedValues>
				<value>0</value>
				<value>1</value>
				<value>2</value>
				<value>3</value>
			</fixedValues>
		</property>
		
		<property name="logLevel" value="DEBUG"
			type="org.ff4j.property.PropertyLogLevel" />
	</properties>

</ff4j>

=== vyomtandon/ff4j/ff4j-webapi-jersey1x/src/test/resources/test-ff4j-features.xml
<!--
  #%L
  ff4j-web
  %%
  Copyright (C) 2013 - 2014 Ff4J
  %%
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  #L%
  -->
<ff4j xmlns="http://www.ff4j.org/schema/ff4j" 
	  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xsi:schemaLocation="http://www.ff4j.org/schema/ff4j http://ff4j.org/schema/ff4j-1.4.0.xsd">

	<features>
		<feature uid="AwesomeFeature" enable="true" description="some desc">
			<flipstrategy class="org.ff4j.strategy.ClientFilterStrategy">
				<param name="grantedClients" value="C1,C2" />
			</flipstrategy>
		</feature>

		<feature uid="first" enable="true" description="description">
			<security>
				<role name="USER" />
			</security>
		</feature>

		<feature-group name="GRP0">
			<feature uid="second" enable="false" description="description">
				<security>
					<role name="USER" />
				</security>
			</feature>
		</feature-group>


		<feature-group name="GRP1">

			<feature uid="forth" enable="true" description="description">
				<flipstrategy class="org.ff4j.strategy.el.ExpressionFlipStrategy">
					<param name="expression" value="third | second" />
				</flipstrategy>
				<security>
					<role name="ADMINISTRATOR" />
					<role name="BETA-TESTER" />
				</security>
			</feature>

			<feature uid="third" enable="false">
				<security>
					<role name="ADMINISTRATOR" />
					<role name="BETA-TESTER" />
				</security>
			</feature>

		</feature-group>

	</features>

	<properties>
		<property name="a" value="AMER">
			<fixedValues>
				<value>AMER</value>
				<value>EAST</value>
				<value>EAST</value>
				<value>EAST</value>
			</fixedValues>
		</property>
		<property name="b" type="int" value="12" />
		<property name="b" type="short" value="12" />
		<property name="c" type="double" value="12.5" />
		<property name="d" type="boolean" value="true" />
		<property name="e" type="string" value="hello" />
		<property name="f" value="12,13,14" />
		<property name="g" type="org.ff4j.property.PropertyLogLevel"
			value="DEBUG" />
		<property name="h" type="float" value="3.4" />
		<property name="i" type="byte" value="a" />
		<property name="j" type="biginteger" value="100000000" />
		<property name="k" type="bigdecimal" value="200000000.1234567" />
		<property name="l" type="long" value="1234567890" />
	</properties>


</ff4j>

=== vyomtandon/ff4j/ff4j-core/src/test/resources/ff4j.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  #%L
  ff4j-core
  %%
  Copyright (C) 2013 Ff4J
  %%
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  #L%
  -->
<ff4j xmlns="http://www.ff4j.org/schema/ff4j" 
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://www.ff4j.org/schema/ff4j ../../main/resources/ff4j-1.4.0.xsd">
	
	<features>
		<feature uid="AwesomeFeature" enable="true" description="some desc" />
	
		<feature uid="first" enable="true" description="description" >
			
			<security>
				<role name="USER" />
			</security>
			
			<custom-properties>
			  <property name="ppint" 	  type="org.ff4j.property.PropertyInt" value="12"   />
			  <property name="ppdouble"   type="double"  value="12.5" />
			  <property name="ppboolean"  type="boolean" value="true" />
			  <property name="ppstring"   value="hello" />
			  <property name="ppListInt"  value="12,13,14" />
			  <property name="myLogLevel" value="DEBUG" type="org.ff4j.property.PropertyLogLevel" />
			  <property name="digitValue" value="1" type="org.ff4j.property.PropertyInt">
			  	<fixedValues>
			 		<value>0</value>
			 		<value>1</value>
			 		<value>2</value>
			 		<value>3</value>
			 	</fixedValues>
			  </property>
			  <property name="regionIdentifier" value="AMER" >
			 	<fixedValues>
			 		<value>AMER</value>
			 		<value>SSSS</value>
			 		<value>EAST</value>
			 		<value>EAST</value>
			 	</fixedValues>
			 </property>
			</custom-properties>
		</feature>
		
		<feature-group name="GRP0">
			<feature uid="second" enable="false" description="description" >
				<security>
					<role name="USER" />
				</security>
			</feature>
		</feature-group>
		
		<feature-group name="GRP1">
			<feature uid="forth" enable="true" description="description" >
				<flipstrategy class="org.ff4j.strategy.el.ExpressionFlipStrategy">
					<param name="expression" value="third | second" />
				</flipstrategy>
				<security>
					<role name="ADMINISTRATOR" />
					<role name="BETA-TESTER" />
				</security>
			</feature>
			<feature uid="third" enable="false" >
				<security>
					<role name="ADMINISTRATOR" />
					<role name="BETA-TESTER" />
				</security>
			</feature>
		</feature-group>
	
	</features>
	
	<properties>	
	
	 <property name="a" value="AMER" >
	 	<fixedValues>
	 		<value>AMER</value>
	 		<value>EAST</value>
	 		<value>EAST</value>
	 		<value>EAST</value>
	 	</fixedValues>
	 </property>
	 
	 <property name="b" 	  value="12"   />
	
	 <property name="c"   value="12.5" />
	
	 <property name="d"  value="true" />
	
	 <property name="e"   value="hello" />
	
	 <property name="f"  value="12,13,14" />
	
	 <property name="g" value="DEBUG" type="org.ff4j.property.PropertyLogLevel" />

	</properties>
	
	
</ff4j>

=== vyomtandon/ff4j/ff4j-store-ehcache/src/test/resources/ff4j-properties.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  #%L
  ff4j-core
  %%
  Copyright (C) 2013 Ff4J
  %%
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  #L%
  -->
<ff4j xmlns="http://www.ff4j.org/schema/ff4j" 
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://www.ff4j.org/schema/ff4j ../../main/resources/ff4j-1.4.0.xsd">
	
	<properties>	
	
	 <property name="a" value="AMER" >
	 	<fixedValues>
	 		<value>AMER</value>
	 		<value>EAST</value>
	 		<value>EAST</value>
	 		<value>EAST</value>
	 	</fixedValues>
	 </property>
	 
	 <property name="b" 	  value="12"   />
	
	 <property name="c"   value="12.5" />
	
	 <property name="d"  value="true" />
	
	 <property name="e"   value="hello" />
	
	 <property name="f"  value="12,13,14" />
	
	 <property name="g" value="DEBUG" type="org.ff4j.property.PropertyLogLevel" />

	</properties>
	
	
</ff4j>
